version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "p0stgr3s"
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: 'redis:7'
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf"
