version: '3'

services:
  redis:
    image: 'redis:7'
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf"
